### ISSUE TITLE
Write unit tests in tests.py that test corner cases and failure cases until you have an average of 3 tests for each function, confirm the expected failures, and add, commit, and push to the private code repo (Project 2)

### ISSUE THREAD

**Issue by wongpeterp** [wongpeterp/cs373-idb#45]
Implement them now

**Comment by mwestdri** [comment]
The private repo, or the public repo? (This might be a typo in the spec)
Also, splitting this up into several problems:
1. Known problem: Modify/augment tests.py tests that test models.py (issue #59).
2. Less known: Create a set of unit tests to test the RESTful API and the underlying DB.(issue #60).
